[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window.padding]
x = 2
y = 2
