# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$kubernetes\
$cmd_duration\
$line_break\
$directory\
$git_branch\
$git_metrics\
$character"""

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = false
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[kubernetes]
style = "cyan dimmed"
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

